parameters:
#    bacula_status.example.class: Bacula\StatusBundle\Example

services:
#    bacula_status.example:
#        class: %bacula_status.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    bacula.twig.blob:
        class: Bacula\StatusBundle\Extension\BlobTwigExtension
        arguments: [ '@service_container' ]
        tags:
          - { name: twig.extension }
